# Generated by Django 2.1.7 on 2019-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')], default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, max_length=6, null=True),
        ),
    ]
