# Generated by Django 2.1.7 on 2019-04-08 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190408_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500000)]),
        ),
    ]
